package au.edu.utas.costing_tool.Enums;

public enum ExpenseType {
    /*
    TRAVEL, FACILITY_HIRE, EQUIPMENT, CONSUMABLES, PARTNER_ORGANISATIONS,
    EXTERNAL_CONTRACTING, RHD_NON_STIPEND, OTHER
    */
    NONE, TRAVEL, FACILITIES_LABORATORY_HIRE, CONSUMABLES, EQUIPMENT_PURCHASES,
    EXTERNAL_CONTRACTOR, OTHER_COSTS, AUDIT_FEES, RHD_NON_STIPEND_COSTS,
    AMC_FACILITY_COSTS, TIA_FACILITY_COSTS, IMAS_FACILITY_COSTS,
    ANIMAL_FACILITY_COSTS, CSL_FACILITY_COSTS, PARTNER_ORGANISATION_1,
    PARTNER_ORGANISATION_2, PARTNER_ORGANISATION_3, PARTNER_ORGANISATION_4
}