package au.edu.utas.costing_tool.Enums;


import lombok.AllArgsConstructor;
import lombok.Getter;


@Getter
@AllArgsConstructor
public enum Facility {
    // AMC Faciltiy Costs
    AUDITORIUM("Auditorium"),
    AUV_REMUS("AUV - Remus"),
    BEAUTY_POINT("Beauty Point Consumables (FRC)"),
    BLUEFIN_CHARTER("Bluefin - bare boat charter"),
    BLUEFIN_OVERNIGHT("Bluefin (full cost - overnight)"),
    BLUEFIN_DAY_SAILING("Bluefin (full cost - day sailing)"),
    BLUEFIN_REPAIRS("Bluefin repairs & maint"),
    BRIDGE_OP_FACILITY("Bridge Op Cubicles - facility hired instead of Bridge Simulator"),
    BRIDGE_OP_SHORT_COURSE("Bridge Op. Cubicles - Short Courses"),
    BRIDGE_OP_STAND_ALONE("Bridge Op. Cubicles - Single Bridge stand alone"),
    BRIDGE_OP_ADD_ON("Bridge Op. Cubicles - Single Bridge, as add-on to hire of main bridge"),
    CAVITATION_TUNNEL("Cavitation Tunnel"),
    CAVITATION_TUNNEL_TECHNICAL("Cavitation Tunnel - Technical"),
    CLASSROOMS_LEVEL_A("Classrooms - level A"),
    CLASSROOMS_LEVEL_B("Classrooms - level B"),
    CLASSROOMS_LEVEL_C("Classrooms - level C"),
    COMPUTER_LABS("Computer Labs"),
    CONSUMABLES("Consumables"),
    COUNCIL_ROOM("Council Room"),
    DIESEL_ENGINE_SIMULATOR("Diesel Engnie Simulator"),
    ECDIS_LABORARTORY("ECDIS Laboratory"),
    FIRE_CENTRE_CLEANING("Fire Fighting Centre - Cleaning"),
    FIRE_CENTRE_CONSUMABLES("Fire Fighting Centre - Consumables"),
    FIRE_CENTRE_HIRE("Fire Fighting Centre - Daily Hire Rate"),
    FULL_MISSION_BRIDGE("Full Mission Bridge Simulator"),
    GMDSS("GMDSS Laboratory"),
    LECTURES_PBB_ERCA_ET("Lectures - PPB and ERCA/ET per hour"),
    LECTURES_PRACTICAL("Lectures - Practical"),
    LECTURES_STANDARD("Lectures - Standard per hour"),
    LIFE_SMALL_BOATS("Life Boats/Small Boats"),
    MDI("MDI"),
    RADAR_SIUMLATOR("Radar Simulator/SOC's"),
    SHIP_SIMULATOR("Ship Simulator"),
    SIMULATOR_MODELLING("Simulator Modelling & Techniques"),
    SURVIVAL_CENTRE_CONSUMABLES("Survival Centre - Consumables"),
    TECHNICIAN("Technician daily rate (FRB, Fire, Survival,MTB,"),
    TOWING_TANK("Towing Tank"),
    TUG_SIMULATOR_STAND_ALONE("Tug Simulator - stand alone for tugmaster training"),
    TUG_SIMULATOR_ADD_ON("Tug Simulator as add-on to Bridge"),

    // TIA Faciltiy Costs
    GLASSHOUSE_SPACE("Glasshouse space (no labour)"),
    GLASSHOUSE_SERVICE("Glasshouse - fully serviced"),
    GROWTH_CHAMBERS("Growth Chambers"),
    GROWTH_CHAMBERS_SERVICE("Growth Chambers fully serviced"),
    LABORATORY_SERVICES("Laboratory Services"),
    LABORATORY_EQUPIMENT("Laboratory Equipment"),
    EQUIPMENT_NON_ELECTRONIC("Equipment (non electronic)"),
    EQUIPMENT_ELECTRONIC("Equipment (electronic)"),
    DEHYDRATOR("Dehydrator"),
    TISSUE_CULTURE_SPACE("Tissue culture lab space"),
    TISSUE_CULTURE_SERVICE("Tissue Culture Lab - fully serviced"),
    COOLROOM("Coolroom"),
    RESEARCH_PLOTS_SMALL("Research Plots <.5 ha - access only"),
    RESEARCH_PLOTS_LARGE("Research Plots >.5 ha - access only"),
    RESEARCH_PLOTS_SERVICE("Research Plots fully services excluding data collection"),
    RESEARCH_PLOTS_SERVICE_DATA("Research Plots fully serviced including data collection"),
    TRACTOR("Tractor and Operator"),
    LABOUR("Labour"),
    MOBILE_PHONES("Mobile Phones"),
    COMPUTERS("computers"),

    // IMAS Facilty Costs
    RV_NAUTICA("RV Nautica base daily charge. Special condition apply"),
    SEABOTIX("Seabotix Remote Operated Vehicle (operational days only, not travel or standby)"),
    UNDERWATER_TOW_CAMERA("Underwater Tow camera (operational days only, not travel or standby)"),
    ISUZU_HIAB("Isuzu truck and large HiAB"),
    RV_TRISH_A("RV Trish (option A)"),
    RV_SEPIA_A("RV Sepia (Option A)"),
    RV_ROOGANAH_A("RV Rooganah (Option A)"),
    RV_LOWINNA_A("RV Losinna (Option A)"),
    RV_MALLANA_A("RV Mallana (Option A)"),
    RV_MORANA_A("RV Morana (Option A)"),
    RV_NOTILUCA_A("RV Notiluca (Option A) - ref PoolCar Manual"),
    HYUNDAI_MAZDA_3_MAZDA_UTE_A("Hyundai, Mazda 3, Mazda ute (Option A)"),
    HILUX_RANGER_UTE_A("Hilux or Ranger ute (Option A)"),
    LAND_CRUISER_A("Land Cruiser V8 (Option A)"),
    FORD_F250_A("Ford F250 (Option A)"),
    RV_TRISH_B_FIXED("RV Trish (Flag Fee, Option B) - Fixed"),
    RV_SEPIA_B_FIXED("RV Sepia (Flag Fee, Option B) - Fixed"),
    RV_ROOGANAH_B_FIXED("RV Rooganah (Flag Fee, Option B) - Fixed"),
    RV_LOWINNA_B_FIXED("RV Losinna (Flag Fee, Option B) - Fixed"),
    RV_MALLANA_B_FIXED("RV Mallana (Flag Fee, Option B) - Fixed"),
    RV_MORANA_B_FIXED("RV Morana (Flag Fee, Option B) - Fixed"),
    RV_NOTILUCA_B_FIXED("RV Notiluca (Flag Fee, Option B) - Fixed - ref PoolCar Manual"),
    HYUNDAI_MAZDA_3_MAZDA_UTE_B_FIXED("Hyundai, Mazda 3, Mazda ute (Flag Fee, Option B) - Fixed"),
    HILUX_RANGER_UTE_B_FIXED("Hilux or Ranger ute (Flag Fee, Option B) - Fixed"),
    LAND_CRUISER_B_FIXED("Land Cruiser V8 (Flag Fee, Option B) - Fixed"),
    FORD_F250_B_FIXED("Ford F250 (Flag Fee, Option B) - Fixed"),
    RV_TRISH_B_VARIABLE("RV Trish (Fuel per hr, Option B) - Variable"),
    RV_SEPIA_B_VARIABLE("RV Sepia (Fuel per hr, Option B) - Variable"),
    RV_ROOGANAH_B_VARIABLE("RV Rooganah (Fuel per hr, Option B) - Variable"),
    RV_LOWINNA_B_VARIABLE("RV Losinna (Fuel per hr, Option B) - Variable"),
    RV_MALLANA_B_VARIABLE("RV Mallana (Fuel per hr, Option B) - Variable"),
    RV_MORANA_B_VARIABLE("RV Morana (Fuel per hr, Option B) - Variable"),
    RV_NOTILUCA_B_VARIABLE("RV Notiluca (Fuel per hr, Option B) - Variable - ref PoolCar Manual"),
    HYUNDAI_MAZDA_3_MAZDA_UTE_B_VARIABLE("Hyundai, Mazda 3, Mazda ute (Fuel per hr, Option B) - Variable"),
    HILUX_RANGER_UTE_B_VARIABLE("Hilux or Ranger ute (Fuel per hr, Option B) - Variable"),
    LAND_CRUISER_B_VARIABLE("Land Cruiser V8 (Fuel per hr, Option B) - Variable"),
    FORD_F250_B_VARIABLE("Ford F250 (Fuel per hr, Option B) - Variable"),
    ICT_CHARGES("ICT Charges (ALL PROJECTS)"),
    DATA_MANAGEMENT_CHARGES("Data Management Charges (ALL PROJECTS)"),
    LAB_FEE_INTENSIVE("Lab User Fee (Intensive)"),
    LAB_FEE_BASIC("Lab User Fee (Basic/Student)"),
    DIVING("Diving"),

    // Menzies Facility Costs
    CLINIC_LARGE("Clinic user 3rd floor - Large"),
    CLINIC_MEDIUM("Clinic user 3rd floor - Medium"),
    CLINIC_SMALL("Clinic user 3rd floor - Small"),
    PHLEBOTOMY_TRAINING("Phlebotomy training - Internal"),
    RESEARCH_NURSE("Research Nurse - Phlebotemis (HEO 5)"),
    LAB("Lab users 5th floor"),
    CYTOMETER_SORTER_UTAS("Flow cytometer sorter - UTAS reseracher rate"),
    CYTOMETER_SORTER_NON_UTAS("Flow cytometer sorter - non-UTAS user rate"),
    CYTOMETER_ANALYSER_UTAS("Flow cytometer analyser - UTAS reseracher rate"),
    CYTOMETER_ANALYSER_UTAS_ASSISTED("Flow cytometer analyser - Assisted UTAS reseracher rate"),
    CYTOMETER_ANALYSER_NON_UTAS("Flow cytometer analyser - non-UTAS user rate"),
    FACS("5mL non-sterile FACS tubes (500 per bag)"),
    DATA_ANALYSIS_TRAINING("Data analysis training - Non-UTAS user rate"),
    MICROSCOPE_PE("PE Spinning Disk microscope"),
    MICROSCOPE_ZEISS("Zeiss Confocal microscope"),
    MICROSCOPE_NIKON("Nikon Live Cell microscope"),
    MICROSCOPE_OLYMPUS("Olympus BX50 microscope"),
    MICROSCOPE_LEICA_LB2("Leica DM LB2 microscope"),
    MICROSCOPE_WIDEFIELD("Widefield Microscope (Leica and Olympus)"),
    MICROSCOPE_MULTIPHOTON("Scientifica Multiphoton microscope"),
    MICROSCOPE_TRANSMISSION_ELECTRON("Transmission Electron microscope"),
    PROECESSING_COST("Cost of processing"),
    SECTIONING_COST("Cost of sectioning"),
    CONTRASTING_GRID_COST("Cost of contrasting grids with heavy metals"),
    COMPUTER_LAPTOP("Std. Computer/laptop (inc. software)"),
    COMPUTER_DESKTOP("Std. Computer/desktop (inc. software)"),
    WIDESCREEN_LCD("Widescreen LCD"),
    STATIONERY("Stationery"),
    TELEPHONE_COST("Telephone cost - per staff"),
    CLEAN_MAIL("\"Clean Mail\" postage"),
    UNCLEAN_MAIL("Postage (not within the clean mail format)"),
    PARCEL_SATCHEL_500G("Parcel Post satchel 500g"),
    PARCEL_SATCHEL_3KG("Parcel Post satchel 3kg"),
    LETTER_C5("Express Post Letter C5 (500 g)"),
    LETTER_B4("Express Post Letter B4 (500g)"),
    EXPRESS_SATCHEL_500G("Express Post satchel 500g"),
    EXPRESS_SATCHEL_3KG("Express Post satchel 3kg"),
    LETTER_LARGE("Large Letters - C5 and B4 <20mm, 260mm x 360mm"),
    // TODO(Andrew): what are these?
    MASS_125G("up to 125g"),
    MASS_126G_250G("126g - 250g"),
    MASS_251G_500G("251g - 500g"),
    PARCEL_REGULAR("Regular Parcels >20mm"),
    MASS_500G("up to 500g"),
    MASS_500G_22KG_TASMANiA("500g - 22kg (within Tasmania only)"),
    MASS_500G_22KG_INTERSTATE("500g - 22kg (Interstate)"),
    MAILING_TUBES("Mailing Tubes - Parcel - Airmail up to 500g - Standard"),
    NZ_ZONE("NZ - (Asia Pacific) - Zone 1"),
    CHINA_ZONE("CHINA - (Asia Pacific - Zone 2"),
    USA_ZONE("USA - (Rest of the world) - Zone 4"),
    REPLY_PAID("Reply Paid"),
    SMALL_DL("Small DL"),
    // TODO(Andrew): repeat of MASS_125G, etc. here
    PACKAGES_500G("Packages up to 500G"),
    QUESTIONNAIRE_PRINTING("Questionnaire printing"),
    BLOOD_SAMPLE("Blood sample - test tube"),
    BMD_SCAN("Bone Mineral Density (BMD) scan (Menzies equipment)"),
    MRI("MRI"),
    X_RAY("X-ray (Hand, hip, knee)"),
    CT_SCAN_HR("High Resolution CT Scan"),
    CT_SCAN_MICRO("MicroCT Scan (Menzies equipment)"),
    CATERING("Catering"),
    FLEET_VEHICLE("Fleet Vehicle (Institute car more than 2 liters)"),
    HIRE_VEHICLE("Hire Vehicle Large Sedan"),
    TELEFORM_DESIGN("Teleform questionnaire design (based upon 10 pages per questionnaire)"),
    TELEFORM_VERIFICATION("Teleform scanning and verifying (based upon 10 pages per questionnaire)"),
    STATISTICAL_SUPPORT_SENIOR("Statistical support - Senior biostatistician"),
    STATISTICAL_SUPPORT_OTHER("Statistical support - Other biostatisticians"),
    HEALTH_ECONOMICS_SUPPORT_PROFESSOR("Health economics support - Professsor"),
    HEALTH_ECONOMICS_SUPPORT_OTHER("Health economics support - Other health economists"),
    DATABASE_DEVELOPMENT("Database development and support"),
    GENEALOGIST("Genealogist"),

    // Animals Facilities
    AGISTMENT("Agistment - mouse cages"),
    MICE_ADULT("Adult mice"),
    MICE_TIME_MATED("Time Mated mice"),
    MICE_TIME_MATED_FEMALES("Own mice Time Mate females"),
    MICE_NEONATE("Adult mice"),
    RAT_ADULT("Adult rat each"),
    RAT_TIME_MATED("Time Mated rat each"),
    RAT_NEONATE("Neonate rat each"),
    MOUSE_CAGE("Mouse cage"),
    RAT_CAGE("Rat cage"),
    MOUSE_CAGE_QUARANTINE("Quarantine mice cage"),
    MOUSE_CAGE_VIROLOGY("Virology mosue cages - disposable"),
    TECHNICAL_FEE_BASIC("Basic Technical Fee (tailing, earclipping, IP injections etc)"),
    TECHNICAL_FEE_ADVANCED("Advanced Technical Fee (I.V., bleeding, dissections etc)"),
    TIME_MATE_CANCELLATION_FEE("Cancellation Fee for Time mates (if less than 3 weeks notice given)"),
    EMBRYO_TRANSFER("Embryo Transfer: actual costs to aquire transport, and house PLUS"),
    EMBRYO_CRYOPRESERVATION("Embryo cryopreservation"),
    SPERM_CRYOPRESERVATION("Embryo cryoprservation"),
    IVF("IVF"),
    REDERIVATION("Rederivation"),
    FOOD("Food - sold to external organisations"),
    CORN_COB_SAWSDUST("Corn Cob/Sawdust - sold to external organisations"),

    // CSL Facilities
    LIQUID_NITROGEN("Supply of liquid nitrogen"),
    COMPUTING_SUPPORT("Computing Support"),
    CENTRAL_ELECTRONICS_WORKSHOP("Central Electronics Workshop - Labour"),
    MECHANICAL_WORKSHOP("Mechanical Workshop - Labour"),
    LAB_TECH_SUPPORT("General Laboratory Technical Support"),
    ELEMENTAL_ANALYSIS_STANDARD("Elemental Analysis - standard"),
    ELEMENTAL_ANALYSIS_PRE_PACKED("Elemental Analysis - pre-packed"),
    ELEMENTAL_ANALYSIS_HIGH_PRECISION("Elemental Analysis - high precision"),
    ELEMENTAL_ANALYSIS_SPECIAL("Elemental Analysis - special rate"),
    ELEMENTAL_ANALYSIS_COAL("Elemental Analysis - coal analysis"),
    ELECTRON_MICROPROBE_NORMAL("Electron Microprobe (JEOL JXA 8530) - Normal"),
    ELECTRON_MICROPROBE_AFTER_HOURS("Electron Microprobe (JEOL JXA 8530) - After Hours"),
    ELECTRON_MICROPROBE_CARBON("Electron Microprobe (JEOL JXA 8530) - carbon coating"),
    ELECTRON_MICROPROBE_SPUTTER("Electron Microprobe (JEOL JXA 8530) - sputter coating (Au or Pr per batch)"),
    FEI_MLA_NORMAL("FEI MLA 650 - normal"),
    FEI_MLA_AFTER_HOURS("FEI MLA 650 - after hours"),
    FEI_MLA_CARBON("FEI MLA 650 - carbon coating"),
    FEI_MLA_SPUTTER("FEI MLA 650 - sputter coating (Au or Pt)"),
    FSESM_NORMAL("FSESM Hitachi SU-70 - normal"),
    FSESM_AFTER_HOURS("FSESM Hitachi SU-70 - after hours"),
    FSESM_CARBON("FSESM Hitachi SU-70 - carbon coating"),
    FSESM_SPUTTER("FSESM Hitachi SU-70 - sputter coating (Au or Pt)"),
    MICROXRF_NORMAL("MicroXRF (Horiba XRT-7000V) - normal"),
    MICROXRF_AFTER_HOURS("MicroXRF (Horiba XRT-7000V) - after hours"),
    EMXRM_LEADER("EMXRM - STAFF SUPPORT (Facility Leader)"),
    EMXRM_ANALYST("EMXRM - STAFF SUPPORT (Lab Analyst)"),
    ICP_MS_ANALYSIS("ICP-MS Facility - Analysis"),
    ICP_MS_LEADER("ICPMS STAFF SUPPORT (Facility Leader)"),
    FRAGMENT_ANALYSER_INJECTIONS("Molecular Genetics - Fragment Analyser (injections)"),
    FRAGMENT_ANALYSER_PLATES("Molecular Genetics - Fragment Analyser (plates)"),
    FRAGMENT_ANALYSER_GENOMIC("Molecular Genetics - Fragment Analyser (genomic reagent)"),
    FRAGMENT_ANALYSER_DNA("Molecular Genetics - Fragment Analyser (DNA fragment reagent)"),
    FRAGMENT_ANALYSER_RNA("Molecular Genetics - Fragment Analyser (RNA reagent)"),
    GENETICS_LAB("Molecular Genetics - Genetics lab usage (quarterly)"),
    GENETICS_LIQUID_NITROGEN("Molecular Genetics - liquid nitrogen (100ml)"),
    PIRO_NORMAL("PIRO Liquid handling robot - normal"),
    PIRO_50UL("PIRO Liquid handling robot - 50ul"),
    PIRO_200UL("PIRO Liquid handling robot - 200ul"),
    PCR("PCR machine usage"),
    ROTORGENE_NORMAL("Rotogene - Realtime PCR - normal"),
    ROTORGENE_CORBETT("Rotogene - Realtime PCR - Corbett genedisc"),
    ROTORGENE_CORBETT_FILM("Rotogene - Realtime PCR - Corbett genedisc sealing film"),
    BECKMAN_SAMPLES("Sequencer Beckman CEQ - samples"),
    BECKMAN_ROWS("Sequencer Beckman CEQ - rows"),
    BECKMAN_PLATES("Sequencer Beckman CEQ - plates"),
    MYRA("MYRA robot tips"),
    BIOSYSTEMS_SEQUENCER("Applied Biosystems sequencer"),
    CAS_ROBOT("CAS 1200N Robot"),
    CAS_TIPS("CAS 1200N 100ul tips"),
    GENETICS_LEADER("Molecular Genetics - STAFF SUPPORT (Faciltiy Leader)"),
    GENETICS_BIOLOGIST("Molecular Genetics - STAFF SUPPORT (Molecular Biologist)"),
    NMR_400_NORMAL("Nuclear Magnetic Resonance 400 MHz - normal usage"),
    NMR_400_AFTER_HOURS("Nuclear Magnetic Resonance 400 MHz - after hours usage"),
    NMR_600_NORMAL("Nuclear Magnetic Resonance 600 MHz - normal usage"),
    NMR_600_AFTER_HOURS("Nuclear Magnetic Resonance 600 MHz - after hours usage"),
    NMR_600_SAMPLES("Nuclear Magnetic Resonance 600 MHz - samples for NMR QA"),
    NMR_LEADER("Nuclear Magnetic Resonance - STAFF SUPPORT (Facility Leader)"),
    MASS_SPEC_GC("Mass Spectrometer Consumables - GC Insert"),
    MASS_SPEC_VIALS("Mass Spectrometer Consumables - HLPC Vials"),
    UPLC_NORMAL("UPLC - Ultra Performance Liquid Chromatography - normal"),
    UPLC_HR("UPLC 1 HR @ normal hourly rate"),
    UPLC_FILTERS("UPLC - Ultra Performance Liquid Chromatography - Syringe filters"),
    UPLC_CARTRIDGE("UPLC - Ultra Performance Liquid Chromatography - C18 cartridge"),
    UPLC_XEVO_NORMAL("UPLC-Xevo triple quadrupole MS - normal"),
    UPLC_XEVO_GC("UPLC-Xevo triple quadrupole MS - GC insert"),
    UPLC_XEVO_VIALS("UPLC-Xevo triple quadrupole MS - HPLC Vials"),
    UPLC_XEVO_FILTERS("UPLC-Xevo triple quadrupole MS - Syringe filters"),
    UPLC_XEVO_CARTRIDGE("UPLC-Xevo triple quadrupole MS - C18 cartridge"),
    UPLC_XEVO_ESI("UPLC-Xevo triple quadrupole MS - Xevo MS-ESI"),
    UPLC_XEVO_NEG("UPLC-Xevo triple quadrupole MS - Xevo MS-ESI-NEG"),
    UPLC_XEVO_APCI("UPLC-Xevo triple quadrupole MS - Xevo MS-APCI"),
    UPLC_XEVO_MSMS("UPLC-Xevo triple quadrupole MS - Xevo MS-MSMS"),
    UPLC_XEVO_HPLC("UPLC-Xevo triple quadrupole MS - Xevo MS-HPLC"),
    VARIAN_GC_NORMAL("Varian Gas Chromatography - normal"),
    VARIAN_GC_HOURLY("Varian GC - hourly rate"),
    VARIAN_MS_NORMAL("Varian Quadrupole Mass Spectrometer - normal"),



    ; String text;



    //LABS_R_US,
}